apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: internallb-webhook-admission-controller
externalAdmissionHooks:
  - name: internallb-webhook-admission-controller.k8s.io
    rules:
      - operations:
          - CREATE, UPDATE
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - services
    failurePolicy: Ignore
    clientConfig:
      service:
        namespace: default
        name: internallb-webhook-admission-controller
      caBundle: 
        
